info:
  app:
    name: byteme
    version: '0.1'
    grailsVersion: 6.1.0
grails:
  cors:
    enabled: true
    mappings:
      '[/api/**]':
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
  mime:
    disable:
      accept:
        header:
          userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
      - text/html
      - application/xhtml+xml
      js: text/javascript
      json:
      - application/json
      - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
      - application/hal+json
      - application/hal+xml
      xml:
      - text/xml
      - application/xml
  gorm:
    reactor:
      events: false
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
environmets:
  development:
    dataSource:
      #dbCreate: update
      #url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      #driverClassName: org.h2.Driver
      #username: sa
      #password: ''
      #pooled: true
      #jmxExport: true
      #url: jdbc:postgresql://localhost:5432/byteme
      #driverClassName: org.postgresql.Driver
      #username: iu
      #password: iu
      #pooled: true
      #jmxExport: true
  production:
dataSource:
  dbCreate: update
  url: jdbc:postgresql://localhost:5432/byteme
  driverClassName: org.postgresql.Driver
  dialect: org.hibernate.dialect.PostgreSQLDialect
  username: iu
  password: iu
  pooled: true
  jmxExport: true